name: Generate Resume

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use kelvintaywl/action-jsonresume-export
        uses: kelvintaywl/action-jsonresume-export@v1
        name: Export resume as HTML
        with:
          theme: macchiato  # Replace with your desired theme
          resume_filepath: resume.json  # Replace if your file path is different
          output_filepath: output/resume.html  # Replace with desired path

      - name: Commit and Push changes (optional)
        uses: ad-m/github-push-action@v2
        if: github.event.ref == 'refs/heads/main'  # Only push on main branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}